### ISSUE TITLE
Allow `balancetype` to be any string?

### ISSUE THREAD

**Issue by kj7rrv** [CatimaLoyalty/Docs#5]
Would there be any problem with allowing arbitrary strings for `balancetype`?

**Comment by TheLastProject** [comment]
What is the use case for this? Because it would break Catima Android pretty badly.

Most importantly, [each currency has its own amount of digits](https://en.wikipedia.org/wiki/ISO_4217#Active_codes). For example, you can have EUR 1.23, but YEN is always a full number like 123. By using arbitrary strings, it becomes impossible to know from the balancetype how to format the value and what values to allow.

**Comment by kj7rrv** [comment]
Oh okay. I didn't realize it would break it; it was just a thought in case it wouldn't hurt anything.

How should currency signs be encoded? The euro sign always means euro, but the $ sign can mean several currencies.

**Comment by TheLastProject** [comment]
You should never use a currency sign in balancetype. As documented, it needs to be `a valid ISO 4217 value`. See the URL I already linked in my previous reply.

**Comment by kj7rrv** [comment]
Okay. What does the Android app do when you set a currency sign? It shows "Points", then a few currency signs, then the ISO 4217 values in the dropdown.

**Comment by TheLastProject** [comment]
Catima Android first puts all known currencies in a list:
https://github.com/CatimaLoyalty/Android/blob/cae95d257768546dd4069c3a33f80d6112fa671d/app/src/main/java/protect/card_locker/LoyaltyCardEditActivity.java#L306-L308

The reason some of those are symbols is because it is based on the system locale: https://docs.oracle.com/javase/8/docs/api/java/util/Currency.html#getSymbol--

Then, it asks Android for the currency belonging to the user selected OS region(s) and puts those near the top:
https://github.com/CatimaLoyalty/Android/blob/cae95d257768546dd4069c3a33f80d6112fa671d/app/src/main/java/protect/card_locker/LoyaltyCardEditActivity.java#L441-L455

It however stores the actual Currency class in the temporary card:
https://github.com/CatimaLoyalty/Android/blob/cae95d257768546dd4069c3a33f80d6112fa671d/app/src/main/java/protect/card_locker/LoyaltyCardEditActivity.java#L418

Which is saved in the database using getCurrencyCode():
https://github.com/CatimaLoyalty/Android/blob/master/app/src/main/java/protect/card_locker/DBHelper.java#L361

Now that you made me look at the code to double-check the behaviour I think I see a possible bug, actually. So I created https://github.com/CatimaLoyalty/Android/issues/761 so I won't forget to look into that.

**Comment by kj7rrv** [comment]
Okay. Is it okay for the Linux version at first to only support currency codes and not symbols?

**Comment by TheLastProject** [comment]
The symbols are purely visual, it saves and loads currency codes into and from the database. So yeah, that's completely fine.

**Comment by kj7rrv** [comment]
Oh okay, thank you!
